### ISSUE TITLE
allways answer'Error: Failed to fetch'

### ISSUE THREAD

**Issue by wrhsd1** [ioanmo226/chatgpt-web-application#1]
After depley with the introduction, the bot alway show "Error: Failed to fetch", the API was already insert in the .env file.
Thank you

**Comment by ioanmo226** [comment]
Please change API_URL to correct deployed url.
https://github.com/ioanmo226/chatgpt-web-application/blob/94e8a24fc3b768be4d93352da19966c0affc391f/client/assets/js/index.js#L1

**Comment by wrhsd1** [comment]
> Please change API_URL to correct deployed url.
> 
> https://github.com/ioanmo226/chatgpt-web-application/blob/94e8a24fc3b768be4d93352da19966c0affc391f/client/assets/js/index.js#L1

It works, thank you very much

**Comment by ioanmo226** [comment]
You are welcome :-)
