### ISSUE TITLE
The author is great, the current GPT3.5api has been released, please trouble to adapt the interface

### ISSUE THREAD

**Issue by lmuiotctf** [ioanmo226/chatgpt-web-application#10]
The author is great, the current GPT3.5api has been released, please trouble to adapt the interface

**Comment by ioanmo226** [comment]
@lmuiotctf Thanks for your info.
Just pushed new version.
Please check

**Comment by ioanmo226** [comment]
Node `openai-api` doesn't support GPT3.5 yet. Will push new version again once it's ready.

**Comment by lmuiotctf** [comment]
Hello author, currently you use the model created by node, the current GPT3.5 request interface address is https://api.openai.com/v1/chat/completions
So using openai.createCompletion you can't find codex and gpt3.5 models, so you will report the error "Rate limit reached for default-gpt-3.5-turbo in organization org-

**Comment by ioanmo226** [comment]
Yeah, Just implemented.
