### ISSUE TITLE
Error using codex

### ISSUE THREAD

**Issue by renato-lombardo** [ioanmo226/chatgpt-web-application#15]
Selecting codex gives this error:
`
HTTP Error: {"message":"The model: `code-davinci-002` does not exist","type":"invalid_request_error","param":null,"code":"model_not_found"}
`
Maybe the model changed name?

**Comment by ioanmo226** [comment]
Codex is now deprecated. Just removed codex option from select.

![image](https://user-images.githubusercontent.com/77344191/229541213-ee374c10-f51f-4419-9d47-f35ce0434a63.png)
