### ISSUE TITLE
API KEY

### ISSUE THREAD

**Issue by mrpiwal** [ioanmo226/chatgpt-web-application#18]
HTTP Error: {"message":"You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.","type":"invalid_request_error","param":null,"code":null}

**Comment by ioanmo226** [comment]
Set api in .env file

**Comment by ioanmo226** [comment]
https://github.com/ioanmo226/chatgpt-web-application#setup
