### ISSUE TITLE
Hello. What do I need to install inside the server folder?thx

### ISSUE THREAD

**Issue by hktrace** [ioanmo226/chatgpt-web-application#2]
Follow your installation tutorial. Found the server folder missing.If you have time. Can you go over the installation process in detail. Thanks.

**Comment by ioanmo226** [comment]
Nice catch 👍 
Project initially had `server` folder but I decided to move `server` folder files to root folder.
Just need to run `npm install` in root folder.
Just updated readme though.

**Comment by hktrace** [comment]
![20230209152144](https://user-images.githubusercontent.com/24778223/217744667-96f16974-a021-4456-a1a2-8d9149502b07.jpg)
I followed the tutorial you wrote and installed it. After sending the data. The return get-prompt-result gives 500 error.
Is it because I have installed some dependencies less?

**Comment by ioanmo226** [comment]
I guess it's because of openai server issue and might work if you set correct OpenAI api key.

https://community.openai.com/t/continuous-gpt3-api-500-error-the-server-had-an-error-while-processing-your-request-sorry-about-that/42239/14

**Comment by hktrace** [comment]
thx.
