### ISSUE TITLE
Is it convenient to provide a docker version？

### ISSUE THREAD

**Issue by xjtushilei** [ioanmo226/chatgpt-web-application#9]
Is it convenient to provide a docker version？

**Comment by ioanmo226** [comment]
Do we really need docker for this simple Html + Node.js project?

**Comment by rossman22590** [comment]
message: 'This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?',
  type: 'invalid_request_error',
  param: 'model',
  code: null

getting this issue on new api gpt turbo

**Comment by ioanmo226** [comment]
Node openai-api doesn't support GPT3.5 yet. Reverted changes. Will push new version again once it's ready.

**Comment by xjtushilei** [comment]
> Do we really need docker for this simple Html + Node.js project?
Maybe it is. Docker will be more convenient to deploy. I believe there will be more users.
Docker is provided for other similar chat-gtp-ui, which is very convenient to use.

**Comment by rossman22590** [comment]
made a pull request and added docker for convenance.
